# Create a 3x3x3 array with random values

In [1]:
import numpy as np
random_arr= np.random.randint(3,100,size=(3,3,3))

random_arr

array([[[ 8, 29, 16],
        [13, 66, 59],
        [99, 79, 24]],

       [[84, 18, 20],
        [51, 74, 65],
        [75, 54, 21]],

       [[67,  4, 63],
        [34, 96, 87],
        [ 5, 98, 21]]])

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
np.diag([1,2,3,4] , -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix

In [19]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:\n")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("\n\nAfter normalization:\n")
print(x)

Original Array:

[[2.78642432e-01 8.39336381e-01 5.75485799e-01 3.16487801e-01
  4.90856627e-01]
 [6.57945077e-02 9.46169334e-01 9.39175527e-01 4.54008615e-01
  8.38169634e-01]
 [6.73948398e-01 1.98285326e-01 2.45122045e-01 3.32540489e-01
  9.75732831e-01]
 [8.28348400e-01 4.34207474e-01 2.75610367e-01 3.87658772e-04
  3.96350435e-01]
 [5.25560238e-02 9.83193144e-01 4.97743454e-01 1.23239446e-01
  4.32904064e-01]]


After normalization:

[[0.28312293 0.85362641 0.58515968 0.32163042 0.49904989]
 [0.06655116 0.96232845 0.95521228 0.46155721 0.85243926]
 [0.68534491 0.20135995 0.2490161  0.33796396 0.99240917]
 [0.8424462  0.44140964 0.28003782 0.         0.40289028]
 [0.05308107 1.         0.5060572  0.12500112 0.44008343]]


# How to find common values between two arrays?

In [6]:
import numpy as np
array1 = np.array([0, 1, 2, 4, 6])
print("Array 1: ",array1)
array2 = np.array([1, 3, 4])
print("Array 2: ",array2)
print("Common values between the arrays:")
print(np.intersect1d(array1, array2))
np.set_printoptions(threshold=np.inf)

Array 1:  [0 1 2 4 6]
Array 2:  [1 3 4]
Common values between the arrays:
[1 4]


# How to get the dates of yesterday, today and tomorrow?

In [7]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-08-02
Today:  2020-08-03
Tomorrow:  2020-08-04


# Consider two random array A and B, check if they are equal

In [8]:
A = np.array([[1,2],[3,6]])
B = np.array([[1,2],[3,6]])
comparison = A == B
equal_arrays = comparison.all()
print(equal_arrays)

True


# Create random vector of size 10 and replace the maximum value by 0

In [11]:
from numpy import array
print("Random vector of size 10:")
v = np.random.randint(1,20, size = 10)
print(v)
v[v.argmax()] = 0
print("\nReplacing the maximum value by 0:")
print(v)

Random vector of size 10:
[ 1  9  2 17 12 13 14 11 14 11]

Replacing the maximum value by 0:
[ 1  9  2  0 12 13 14 11 14 11]


# How to print all the values of an array?

In [12]:
x = np.arange(101)
np.set_printoptions(threshold=np.inf)
print(x)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


# Subtract the mean of each row of a matrix

In [13]:
import numpy as np
print("Original matrix:\n")
a = np.arange(12).reshape(3,4)
print(a)
print("\nSubtract the mean of each row of the matrix:\n")
b = a - a.mean(axis=1, keepdims = True)
print(b)

Original matrix:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Subtract the mean of each row of the matrix:

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [14]:
#given vector
a = np.random.randint(1,8,8)
print("Given vector:", a)
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

Given vector: [1 3 5 1 3 1 7 7]
Indexing vector: [0 0 0 0 1 2 4 4]
Result: [2 4 6 1 4 1 7 7]


# How to get the diagonal of a dot product?

In [15]:
X = [[1,2],[3,4]]
Y = [[1,2],[3,4]]
Z = np.diag(np.dot(X,Y))
Z

array([ 7, 22])

# How to find the most frequent value in an array?

In [16]:
import numpy as np
x = np.random.randint(0, 10, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[0 0 9 1 2 2 0 6 7 4 3 9 0 4 6 6 2 6 0 2]
Most frequent value in the above array:
0


# How to get the n largest values of an array

In [17]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print("Largest value of the array is",x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
Largest value of the array is [9]


# How to create a record array from a regular array?

In [18]:
import numpy as np
a1=np.array(['Ferrari','Mercedes','McLaren','Red Bull'])
a2=np.array(['Red','Grey','Orange','Blue'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])

('Ferrari', 'Red')
('Mercedes', 'Grey')
('McLaren', 'Orange')
